/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcingNewRouteImport } from './routes/sourcing.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsIdReviewVendorRouteImport } from './routes/events_.$id.review.$vendor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcingNewRoute = SourcingNewRouteImport.update({
  id: '/sourcing/new',
  path: '/sourcing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdReviewVendorRoute = EventsIdReviewVendorRouteImport.update({
  id: '/events_/$id/review/$vendor',
  path: '/events/$id/review/$vendor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/sourcing/new': typeof SourcingNewRoute
  '/events/$id/review/$vendor': typeof EventsIdReviewVendorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/sourcing/new': typeof SourcingNewRoute
  '/events/$id/review/$vendor': typeof EventsIdReviewVendorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/sourcing/new': typeof SourcingNewRoute
  '/events_/$id/review/$vendor': typeof EventsIdReviewVendorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$id'
    | '/sourcing/new'
    | '/events/$id/review/$vendor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$id' | '/sourcing/new' | '/events/$id/review/$vendor'
  id:
    | '__root__'
    | '/'
    | '/events/$id'
    | '/sourcing/new'
    | '/events_/$id/review/$vendor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsIdRoute: typeof EventsIdRoute
  SourcingNewRoute: typeof SourcingNewRoute
  EventsIdReviewVendorRoute: typeof EventsIdReviewVendorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourcing/new': {
      id: '/sourcing/new'
      path: '/sourcing/new'
      fullPath: '/sourcing/new'
      preLoaderRoute: typeof SourcingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id/review/$vendor': {
      id: '/events_/$id/review/$vendor'
      path: '/events/$id/review/$vendor'
      fullPath: '/events/$id/review/$vendor'
      preLoaderRoute: typeof EventsIdReviewVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsIdRoute: EventsIdRoute,
  SourcingNewRoute: SourcingNewRoute,
  EventsIdReviewVendorRoute: EventsIdReviewVendorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
